/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _CLOCK_CONFIG_H_
#define _CLOCK_CONFIG_H_

#include "fsl_common.h"

/*******************************************************************************
 * Definitions
 ******************************************************************************/
#define BOARD_XTAL0_CLK_HZ                          8000000U  /*!< Board xtal0 frequency in Hz */

/*******************************************************************************
 ******************** Configuration clock_config_irc_4mhz **********************
 ******************************************************************************/
/*******************************************************************************
 * Definitions for clock_config_irc_4mhz configuration
 ******************************************************************************/
#define CLOCK_CONFIG_IRC_4MHZ_CORE_CLOCK            4000000U  /*!< Core clock frequency: 4000000Hz */

/*! @brief MCG set for clock_config_irc_4mhz configuration.
 */
extern const mcg_config_t mcgConfig_clock_config_irc_4mhz;
/*! @brief SIM module set for clock_config_irc_4mhz configuration.
 */
extern const sim_clock_config_t simConfig_clock_config_irc_4mhz;
/*! @brief OSC set for clock_config_irc_4mhz configuration.
 */
extern const osc_config_t oscConfig_clock_config_irc_4mhz;

/*******************************************************************************
 * API for clock_config_irc_4mhz configuration
 ******************************************************************************/
#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus*/

/*!
 * @brief This function executes configuration of clocks.
 *
 */
void clock_config_irc_4mhz(void);

#if defined(__cplusplus)
}
#endif /* __cplusplus*/

/*******************************************************************************
 ******************* Configuration clock_config_xtal_94mhz *********************
 ******************************************************************************/
/*******************************************************************************
 * Definitions for clock_config_xtal_94mhz configuration
 ******************************************************************************/
#define CLOCK_CONFIG_XTAL_94MHZ_CORE_CLOCK         94000000U  /*!< Core clock frequency: 94000000Hz */

/*! @brief MCG set for clock_config_xtal_94mhz configuration.
 */
extern const mcg_config_t mcgConfig_clock_config_xtal_94mhz;
/*! @brief SIM module set for clock_config_xtal_94mhz configuration.
 */
extern const sim_clock_config_t simConfig_clock_config_xtal_94mhz;
/*! @brief OSC set for clock_config_xtal_94mhz configuration.
 */
extern const osc_config_t oscConfig_clock_config_xtal_94mhz;

/*******************************************************************************
 * API for clock_config_xtal_94mhz configuration
 ******************************************************************************/
#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus*/

/*!
 * @brief This function executes configuration of clocks.
 *
 */
void clock_config_xtal_94mhz(void);

#if defined(__cplusplus)
}
#endif /* __cplusplus*/

/*******************************************************************************
 ******************* Configuration clock_config_xtal_168mhz ********************
 ******************************************************************************/
/*******************************************************************************
 * Definitions for clock_config_xtal_168mhz configuration
 ******************************************************************************/
#define CLOCK_CONFIG_XTAL_168MHZ_CORE_CLOCK       168000000U  /*!< Core clock frequency: 168000000Hz */

/*! @brief MCG set for clock_config_xtal_168mhz configuration.
 */
extern const mcg_config_t mcgConfig_clock_config_xtal_168mhz;
/*! @brief SIM module set for clock_config_xtal_168mhz configuration.
 */
extern const sim_clock_config_t simConfig_clock_config_xtal_168mhz;
/*! @brief OSC set for clock_config_xtal_168mhz configuration.
 */
extern const osc_config_t oscConfig_clock_config_xtal_168mhz;

/*******************************************************************************
 * API for clock_config_xtal_168mhz configuration
 ******************************************************************************/
#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus*/

/*!
 * @brief This function executes configuration of clocks.
 *
 */
void clock_config_xtal_168mhz(void);

#if defined(__cplusplus)
}
#endif /* __cplusplus*/

#endif /* _CLOCK_CONFIG_H_ */

